### PR TITLE
add unmarshal function to handle extra event fields

### PR DESCRIPTION
**Pull request by bkleiner**
some of spontaneous mpv events, like `start-file`, contain [additional fields](https://mpv.io/manual/stable/#command-interface-playlist-entry-id) in the event payload.
this pr adds a custom unmarshal function for the `Event` struct to stuff all unnamed fields into a new attribute `ExtraData`, making this data available to the event consumers.

### CODE REVIEW

**Comment by dexterlb** [comment]
Hmm, this seems necessary indeed.

However, I wonder if there's a way to avoid iterating all fields with reflect every time we get an event? For example, precompute the set of names that appear as json tags once, and then just check which keys of the map are in the set (which avoids calling into reflect on every event)?

**Comment by bkleiner** [comment]
certainly, probably just run the reflect code in an `init()` and put it all into a global map, i will update this pr with those changes.
i just figured i keep the impact on the codebase as self contained as possible.

**Comment by dexterlb** [comment]
Thanks!

Better to keep the overall codebase more sensible than to strive to make individual changes more self-contained, imo

**Comment by bkleiner** [comment]
yeah, i concur, however, often its easier to get a pr merged when then diff is nice and compact :)

**Comment by dexterlb** [comment]
I shall not dispute further, for your words indeed bear much wisdom

**Comment by bkleiner** [comment]
updated the branch for a variant with a global.

**Comment by dexterlb** [comment]
Great, all seems ok

**Pull request merged**
